version: '3.9'
services:
  xray-core:
    image: teddysun/xray
    container_name: xray-external
    volumes:
      - $PWD:/etc/xray
      - $PWD/iran.dat:/usr/bin/iran.dat
      - $PWD/cert:/root/cert
      - /dev/shm/:/dev/shm/
    restart: always
    network_mode: host